### ISSUE TITLE
从112版本开始，双击关闭就存在BUG

### ISSUE THREAD

**Issue by oyksoft** [icy37785/chrome_plus#3]
chrome 112版本开始（目前是Beta），只要有一个标签页设置成“固定”，那么**双击关闭标签页**就整体失效。而111版本是正常的。希望能够改改代码维护一下，谢谢哦。

**Comment by Itzamana** [comment]
112稳定版没有复现

**Comment by oyksoft** [comment]
> 112稳定版没有复现

这问题也是奇怪，现在不知道是谷歌那边修改了什么，已经变正常了。暂且关闭此条。
